// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { existsSync, readFileSync } from "node:fs";
import { defineConfig } from "prisma/config";

type InitialMockSettings = {
  SHOPIFY_WEBHOOK_SIGNING_SECRET?: string;
  SHOPIFY_ADMIN_TOKEN?: string;
  SHOPIFY_SHOP_DOMAIN?: string;
  STRIPE_SECRET_KEY?: string;
  STRIPE_WEBHOOK_SIGNING_SECRET?: string;
};

function appendInitialMockOptions(databaseUrl: string | undefined) {
  if (!databaseUrl) return databaseUrl;

  const mockPath = new URL("./initial_mock.json", import.meta.url);
  if (!existsSync(mockPath)) return databaseUrl;

  const mock = JSON.parse(readFileSync(mockPath, "utf8")) as InitialMockSettings;
  const settings: Array<[string, string | undefined]> = [
    [
      "app.shopify_integration_encryption_key",
      process.env["SHOPIFY_INTEGRATION_ENCRYPTION_KEY"],
    ],
    [
      "app.payment_provider_encryption_key",
      process.env["PAYMENT_PROVIDER_ENCRYPTION_KEY"],
    ],
    [
      "app.initial_mock.shopify_webhook_signing_secret",
      mock.SHOPIFY_WEBHOOK_SIGNING_SECRET,
    ],
    ["app.initial_mock.shopify_admin_token", mock.SHOPIFY_ADMIN_TOKEN],
    ["app.initial_mock.shopify_shop_domain", mock.SHOPIFY_SHOP_DOMAIN],
    ["app.initial_mock.stripe_secret_key", mock.STRIPE_SECRET_KEY],
    [
      "app.initial_mock.stripe_webhook_signing_secret",
      mock.STRIPE_WEBHOOK_SIGNING_SECRET,
    ],
  ];

  if (settings.some(([, value]) => !value?.trim())) return databaseUrl;

  const url = new URL(databaseUrl);
  const existingOptions = url.searchParams.get("options")?.trim();
  const seedOptions = settings.map(([name, value]) => `-c ${name}=${value}`);
  url.searchParams.set(
    "options",
    existingOptions ? [existingOptions, ...seedOptions].join(" ") : seedOptions.join(" "),
  );
  return url.toString();
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: appendInitialMockOptions(process.env["DATABASE_URL"]),
  },
});
